
import './General.scss'
import './Navbar.scss'
import './Settings.scss'
import './Timer.scss'
import './Home.scss'
import './Buttons.scss'
import './Try.scss'
import './Why.scss'
import './How.scss'
import './Leftarrow.scss'
import './Congrats.scss'
import './Benefit.scss'
import './CTA.scss'
import './Footer.scss'
